[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes --no-install-recommends ca-certificates gnupg curl",
    "curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -",
    "echo 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main' > /etc/apt/sources.list.d/llvm12.list",
    "apt-get update",
    "apt-get install --assume-yes --no-install-recommends clang-12 libclang-12-dev libv4l-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH libudev-dev:$CROSS_DEB_ARCH",
]