[package]
name = "carui-cameras"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "carui-cameras"
path = "src/main.rs"

[dependencies]
carui-common.workspace = true
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
futures-util.workspace = true
async-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
chrono.workspace = true
uuid.workspace = true
parking_lot.workspace = true

v4l.workspace = true

tokio-util = { version = "0.7", features = ["io"] }

image = { version = "0.24", features = ["jpeg", "png"] }
imageproc = "0.23"
rusttype = "0.9"
bytes = "1.5"
crossbeam-channel = "0.5"
walkdir = "2.5.0"
tokio-stream = { version = "0.1", features = ["sync"] }
fast_image_resize = "6.0.0"

[profile.dev]
lto = true
codegen-units = 1
strip = true

[profile.release]
lto = true
codegen-units = 1
strip = true
