
listen_addr = "0.0.0.0:8084"

gpio_chip = "gpiochip0"

[doors]
front_left = 17
front_right = 27
rear_left = 22
rear_right = 23

[reverse]
signal = 24

[parking]
port = "/dev/ttyUSB0"
baud_rate = 9600
poll_interval_ms = 100


[[parking.sensors]]
position = "rear_left"
uart_index = 0

[[parking.sensors]]
position = "rear_center_left"
uart_index = 1

[[parking.sensors]]
position = "rear_center_right"
uart_index = 2

[[parking.sensors]]
position = "rear_right"
uart_index = 3


